# TODO: use a smaller docker image for the production app
FROM mcr.microsoft.com/devcontainers/cpp:1-debian-11

# install libasio
RUN apt-get install -y libasio-dev

# install Crow
RUN wget https://github.com/CrowCpp/Crow/archive/refs/tags/v1.3.0.tar.gz && \
    tar -xzf ./v1.3.0.tar.gz && \
    cd ./Crow-1.3.0 && \
    mkdir build && cd build && \
    cmake .. -DCROW_BUILD_EXAMPLES=OFF -DCROW_BUILD_TESTS=OFF -DCROW_ENABLE_SSL=OFF && \
    make install
RUN rm -rf ./v1.3.0.tar.gz ./Crow-1.3.0


# install libtinyxml2
RUN apt-get install -y libtinyxml2-dev=8.0.0+dfsg-2


# install paho.mqtt.c and paho.mqtt.cpp
RUN git clone https://github.com/eclipse/paho.mqtt.cpp && \
    cd paho.mqtt.cpp && \
    git checkout v1.5.3 && \
    git submodule init && \
    git submodule update && \
    cmake -Bbuild -H. -DPAHO_WITH_MQTT_C=ON -DPAHO_BUILD_EXAMPLES=OFF -DPAHO_WITH_SSL=OFF && \
    cmake --build build/ --target install
RUN rm -rf ./paho.mqtt.cpp


# install libcpr
RUN wget https://github.com/libcpr/cpr/archive/refs/tags/1.12.0.tar.gz && \
    tar -xzf ./1.12.0.tar.gz && \
    cd ./cpr-1.12.0/ && mkdir build && cd build && \
    cmake -DCPR_ENABLE_SSL=OFF -DCPR_USE_SYSTEM_CURL=ON .. && \
    cmake --build . --parallel && \
    cmake --install .
RUN rm -rf ./1.12.0.tar.gz ./cpr-1.12.0/


COPY build/gate_app /usr/bin/gate_app

CMD ["/usr/bin/gate_app"]
